---
# This simple playbook world update all of my Raspberry Pi's
# This is the command I need to update every machine:
# ansible-playbook -i hosts update.yml --ask-pass --sudo
# This is to command a need to update as one machine from the hosts file, 
# fourth being the name of the raspberry targeting:
#  ansible-playbook -i hosts update.yml --ask-pass --sudo --limit fourth
# change hosts: line to reflect which host acts on

- hosts: all
  sudo: yes
  user: pi

  tasks:
    - name: Let's update the apt cache.
      apt: update_cache=yes

    - name: Now we need to upgrade the Raspbian distribution.
      apt: upgrade=yes

    - name: Autoremove any unused packages.
      shell: "apt-get autoremove --assume-yes --purge"

    - name: Let's Autoclean the system.
      shell: "apt-get autoclean --assume-yes"

    - name: Final greeting upon successful update and upgrade.
      pause: prompt="Hopefully all of the Raspberry Pi's have been updated!."
